# Reviews Text Sentiment Analysis For Thailand Tourism Recommendation

This project target for create recommendation system from rating thailand tourism by learning review positive or negative

#### Step #1 - Setup Project Library Package

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk
import os
from geopy.geocoders import Nominatim
from dotenv import load_dotenv

load_dotenv()

True

#### Step #2 - Data Preparation
##### 2.1 Thailand Province -> Amphure Data <br>
https://github.com/kongvut/thai-province-data

In [2]:
province_data = pd.read_json('hook/data/api_province_with_amphure_tambon.json')
province_data

,id,name_th,name_en,geography_id,created_at,updated_at,deleted_at,amphure
0,1,กรุงเทพมหานคร,Bangkok,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 1001, 'name_th': 'เขตพระนคร', 'name_en..."
1,2,สมุทรปราการ,Samut Prakan,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 1101, 'name_th': 'เมืองสมุทรปราการ', '..."
2,3,นนทบุรี,Nonthaburi,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 1201, 'name_th': 'เมืองนนทบุรี', 'name..."
3,4,ปทุมธานี,Pathum Thani,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 1301, 'name_th': 'เมืองปทุมธานี', 'nam..."
4,5,พระนครศรีอยุธยา,Phra Nakhon Si Ayutthaya,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 1401, 'name_th': 'พระนครศรีอยุธยา', 'n..."
...,...,...,...,...,...,...,...,...
72,73,พัทลุง,Phatthalung,6,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 9301, 'name_th': 'เมืองพัทลุง', 'name_..."
73,74,ปัตตานี,Pattani,6,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 9401, 'name_th': 'เมืองปัตตานี', 'name..."
74,75,ยะลา,Yala,6,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 9501, 'name_th': 'เมืองยะลา', 'name_en..."
75,76,นราธิวาส,Narathiwat,6,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 9601, 'name_th': 'เมืองนราธิวาส', 'nam..."
76,77,บึงกาฬ,Bueng Kan,3,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 3801, 'name_th': 'เมืองบึงกาฬ', 'name_..."

In [3]:
central_province_data = province_data[province_data['geography_id'] == 2]
central_province_data

,id,name_th,name_en,geography_id,created_at,updated_at,deleted_at,amphure
0,1,กรุงเทพมหานคร,Bangkok,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 1001, 'name_th': 'เขตพระนคร', 'name_en..."
1,2,สมุทรปราการ,Samut Prakan,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 1101, 'name_th': 'เมืองสมุทรปราการ', '..."
2,3,นนทบุรี,Nonthaburi,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 1201, 'name_th': 'เมืองนนทบุรี', 'name..."
3,4,ปทุมธานี,Pathum Thani,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 1301, 'name_th': 'เมืองปทุมธานี', 'nam..."
4,5,พระนครศรีอยุธยา,Phra Nakhon Si Ayutthaya,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 1401, 'name_th': 'พระนครศรีอยุธยา', 'n..."
5,6,อ่างทอง,Ang Thong,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 1501, 'name_th': 'เมืองอ่างทอง', 'name..."
6,7,ลพบุรี,Loburi,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 1601, 'name_th': 'เมืองลพบุรี', 'name_..."
7,8,สิงห์บุรี,Sing Buri,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 1701, 'name_th': 'เมืองสิงห์บุรี', 'na..."
8,9,ชัยนาท,Chai Nat,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 1801, 'name_th': 'เมืองชัยนาท', 'name_..."
9,10,สระบุรี,Saraburi,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 1901, 'name_th': 'เมืองสระบุรี', 'name..."
16,17,นครนายก,Nakhon Nayok,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 2601, 'name_th': 'เมืองนครนายก', 'name..."
46,47,นครสวรรค์,Nakhon Sawan,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 6001, 'name_th': 'เมืองนครสวรรค์', 'na..."
47,48,อุทัยธานี,Uthai Thani,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 6101, 'name_th': 'เมืองอุทัยธานี', 'na..."
48,49,กำแพงเพชร,Kamphaeng Phet,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 6201, 'name_th': 'เมืองกำแพงเพชร', 'na..."
50,51,สุโขทัย,Sukhothai,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 6401, 'name_th': 'เมืองสุโขทัย', 'name..."
51,52,พิษณุโลก,Phitsanulok,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 6501, 'name_th': 'เมืองพิษณุโลก', 'nam..."
52,53,พิจิตร,Phichit,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 6601, 'name_th': 'เมืองพิจิตร', 'name_..."
53,54,เพชรบูรณ์,Phetchabun,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 6701, 'name_th': 'เมืองเพชรบูรณ์', 'na..."
56,57,สุพรรณบุรี,Suphan Buri,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 7201, 'name_th': 'เมืองสุพรรณบุรี', 'n..."
57,58,นครปฐม,Nakhon Pathom,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 7301, 'name_th': 'เมืองนครปฐม', 'name_..."
58,59,สมุทรสาคร,Samut Sakhon,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 7401, 'name_th': 'เมืองสมุทรสาคร', 'na..."
59,60,สมุทรสงคราม,Samut Songkhram,2,2019-08-09 03:33:09+07:00,2022-05-16 06:31:03+07:00,NaT,"[{'id': 7501, 'name_th': 'เมืองสมุทรสงคราม', '..."

In [ ]:
provinces = central_province_data['name_en'].tolist()
geolocator = Nominatim(user_agent="thailand_provinces")
data = {'Province': [], 'Latitude': [], 'Longitude': []}

for province in provinces:
    location = geolocator.geocode(f"{province}, Thailand")
    if location:
        data['Province'].append(province)
        data['Latitude'].append(location.latitude)
        data['Longitude'].append(location.longitude)

thailland_province_coordinates = pd.DataFrame(data)

In [5]:
# thailland_province_coordinates.to_csv("thailand_province_coordinate.csv", index=False, header=True, sep=',', encoding='utf-8')

In [8]:
thailland_province_coordinates[thailland_province_coordinates['Province'] == 'Bangkok']

  Province   Latitude   Longitude
0  Bangkok  13.752494  100.493509

 ##### 2.2 Thailand Tourism Location API Data <br>
https://developers.tourismthailand.org/

In [ ]:
import hook.thai_tourism_data as tat
tourism_location = tat.ThaiTourismAPI("EN")

def getTourismLocationsByProvince(province_name, province_location, category):
    search_params = {
            "keyword": "",  # Example keyword for Kanchanaburi
            "location": province_location,
            "categorycodes": category,
            "province_name": province_name,
            "radius": 1000,
            "number_of_result": 100,
            "page_number": 1,
            "destination": province_name,
            "filter_by_update_date": "2019/09/01-2024/05/31"
        }
    tourism_data = tourism_location.fetch_search_location(**search_params)

    df = pd.DataFrame([vars(place) for place in tourism_data])
    return df

In [5]:
thailland_province_coordinates = pd.read_csv("dataset/thailand_province_coordinate.csv")

In [10]:
tourism_attraction_locations = pd.DataFrame()
tourism_hotels_locations = pd.DataFrame()
tourism_restaurants_locations = pd.DataFrame()
tourism_shops_locations = pd.DataFrame()
# CATEGORIES: ATTRACTION | ACCOMMODATION  | RESTAURANT | GEOS | SHOP

for index, pvn in province_data.iterrows():
    coordinate = thailland_province_coordinates[thailland_province_coordinates['Province'] == pvn['name_en']]
    
    if len(coordinate['Latitude'].values) > 0:
        # tourism_shops_location = getTourismLocationsByProvince(pvn['name_th'], 
        # f"{coordinate['Latitude'].values[0]},"
        # f"{coordinate['Longitude'].values[0]}",
        # "SHOP")
        
        # tourism_shops_locations = pd.concat([tourism_shops_locations, tourism_shops_location], ignore_index=True)
        
        province_torism_location = getTourismLocationsByProvince(pvn['name_en'], 
        f"{coordinate['Latitude'].values[0]},"
        f"{coordinate['Longitude'].values[0]}",
        "ATTRACTION")
        
        tourism_attraction_locations = pd.concat([tourism_attraction_locations, province_torism_location], ignore_index=True)
        
        # tourism_hotels_location = getTourismLocationsByProvince(pvn['name_en'], 
        # f"{coordinate['Latitude'].values[0]},"
        # f"{coordinate['Longitude'].values[0]}",
        # "ACCOMMODATION")
        
        # tourism_hotels_locations = pd.concat([tourism_hotels_locations, tourism_hotels_location], ignore_index=True)
        
        # tourism_restaurants_location = getTourismLocationsByProvince(pvn['name_th'], 
        # f"{coordinate['Latitude'].values[0]},"
        # f"{coordinate['Longitude'].values[0]}",
        # "RESTAURANT")
        
        # tourism_restaurants_locations = pd.concat([tourism_restaurants_locations, tourism_restaurants_location], ignore_index=True)

In [ ]:
tourism_shops_locations

In [ ]:
tourism_attraction_locations

In [ ]:
tourism_hotels_locations

In [ ]:
tourism_restaurants_locations

In [12]:
# tourism_shops_locations.to_csv("tourism_shops_locations.csv", index=False, na_rep='N/A', header=True, sep=',', encoding='utf-8')

tourism_attraction_locations.to_csv("central_tourism_attraction_locations_en.csv", index=False, na_rep='N/A', header=True, sep=',', encoding='utf-8')

# tourism_hotels_locations.to_csv("tourism_hotels_locations.csv", index=False, na_rep='N/A', header=True, sep=',', encoding='utf-8')

# tourism_restaurants_locations.to_csv("tourism_restaurants_locations.csv", index=False, na_rep='N/A', header=True, sep=',', encoding='utf-8')

In [6]:
central_tourism_attraction_locations = pd.read_csv("dataset/central_tourism_attraction_locations_en.csv")
central_tourism_attraction_locations

,place_id,place_name,latitude,longitude,category_code,category_description,sha_name,sha_type_code,sha_type_description,sha_cate_id,...,address,sub_district,district,province,postcode,thumbnail_url,destination,tags,distance,update_date
0,P03013220,Wat Ratchabophit Sathitmahasimaram,13.749132,100.497341,ATTRACTION,Attraction,NaN,NaN,NaN,NaN,...,2 Fueang Nakhon Road,Wat Ratchabophit,Phra Nakhon,Bangkok,10200.0,https://tatapi.tourismthailand.org/tatfs/Image...,BANGKOK,NaN,0.0,2024-05-27T14:30:11.51
1,P03013472,Wat Yan Nawa,13.717333,100.513552,ATTRACTION,Attraction,NaN,NaN,NaN,NaN,...,40 Charoen Krung Road,Yan Nawa,Sathon,Bangkok,10120.0,https://tatapi.tourismthailand.org/tatfs/Image...,BANGKOK,NaN,0.0,2024-05-24T15:09:37.447
2,P03013449,Tiger God Shrine,13.753852,100.498319,ATTRACTION,Attraction,NaN,NaN,NaN,NaN,...,468 Tanao Road,San Chaopho Suea,Phra Nakhon,Bangkok,10200.0,https://tatapi.tourismthailand.org/tatfs/Image...,BANGKOK,NaN,0.0,2024-05-24T15:04:50.82
3,P03013827,Wat Thewarat Kunchorn Worawiharn,13.772303,100.501957,ATTRACTION,Attraction,NaN,NaN,NaN,NaN,...,NaN,Wachira Phayaban,Dusit,Bangkok,10300.0,https://tatapi.tourismthailand.org/tatfs/Image...,BANGKOK,NaN,0.0,2024-05-24T14:40:56.073
4,P03013469,Wat Apson Sawan Worawihan,13.720030,100.469886,ATTRACTION,Attraction,NaN,NaN,NaN,NaN,...,NaN,Pak Khlong Phasi Charoen,Phasi Charoen,Bangkok,10160.0,https://tatapi.tourismthailand.org/tatfs/Image...,BANGKOK,NaN,0.0,2024-05-24T14:33:22.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
974,P03009110,Baan Kru Eua,13.426838,99.955975,ATTRACTION,Attraction,NaN,NaN,NaN,NaN,...,193-195,Amphawa,Amphawa,Samut Songkhram,75110.0,https://tatapi.tourismthailand.org/tatfs/Image...,Samut Songkhram,NaN,0.0,2020-02-19T19:30:00
975,P03013094,Bang Nok Khwaek Floating Market,13.496121,99.922127,ATTRACTION,Attraction,NaN,NaN,NaN,NaN,...,NaN,Bang Nok Khwaek,Bang Khonthi,Samut Songkhram,75120.0,https://tatapi.tourismthailand.org/tatfs/Image...,Samut Songkhram,NaN,0.0,2020-02-19T19:30:00
976,P03005443,Wat Intaram,13.441012,99.920636,ATTRACTION,Attraction,NaN,NaN,NaN,NaN,...,NaN,Mueang Mai,Amphawa,Samut Songkhram,75110.0,https://tatapi.tourismthailand.org/tatfs/Image...,Samut Songkhram,NaN,0.0,2020-02-18T19:30:00
977,P03012297,Tao Thai Doem 2,13.470109,99.967479,ATTRACTION,Attraction,NaN,NaN,NaN,NaN,...,NaN,Bang Krabue,Bang Khonthi,Samut Songkhram,75120.0,https://tatapi.tourismthailand.org/tatfs/Image...,Samut Songkhram,NaN,0.0,2020-02-13T08:00:00
978,P03000251,Thai Dessert Museum,13.423970,99.955629,ATTRACTION,Attraction,NaN,NaN,NaN,NaN,...,NaN,Amphawa,Amphawa,Samut Songkhram,75110.0,https://tatapi.tourismthailand.org/tatfs/Image...,Samut Songkhram,NaN,0.0,2020-02-12T08:00:00

##### 2.3 TripAdvisor API Data <br>
https://tripadvisor-content-api.readme.io/reference/getlocationdetails

In [2]:
from hook.tripadvisor_data import TripAdvisorApi

load_dotenv()

# Ensure the API key is set
api_key = os.getenv('TRIPADVISOR_API_KEY')

# Initialize the API client
TripAdvisor_api = TripAdvisorApi(api_key, "EN")
# print(thai_tourism_api)

# Test API request
# response = thai_tourism_api.test_api_request()

In [9]:

response = TripAdvisor_api.location_search(
    "tk park",
    "attractions",
    None,
    "thailand",
    None,
    1000,
    "km",
    "en"
)
response.json()['data'][0]["location_id"]
location = response.json()['data']
# df_location = pd.concat(pd.DataFrame({"location_id": location['location_id'], "name": location['name']}))
# df_location

In [10]:
location

[{'location_id': '1997527',
  'name': 'TK Tour',
  'address_obj': {'city': 'Ko Samui',
   'state': 'Surat Thani Province',
   'country': 'Thailand',
   'postalcode': '84310',
   'address_string': '84310 Thailand'}}]

In [37]:

pd.DataFrame(pd.json_normalize(location))

,location_id,name,address_obj.street1,address_obj.city,address_obj.state,address_obj.country,address_obj.address_string
0,16735656,Address Sky View,Sheikh Mohammed Bin Rashed Boulevard,Dubai,Emirate of Dubai,United Arab Emirates,"Sheikh Mohammed Bin Rashed Boulevard, Dubai Un..."

In [ ]:
# tourism_attraction_locations
tripadvisor_central_attraction_locations = pd.DataFrame(columns=["location_id", "name", "province", "place_id"])

for index, attraction in central_tourism_attraction_locations.iterrows():

    response = TripAdvisor_api.location_search(
        attraction["place_name"],
        "attractions",
        None,
        "thailand",
        None,
        1000,
        "km",
        "en"
    )
    
    locations = response.json()['data']
    
    if len(locations) == 0:
        continue
    
    for sub_index, location in pd.DataFrame(pd.json_normalize(locations)).iterrows():
        
        print(f">>> #{index}/{sub_index} [$$$ {attraction['province']} | $$$ {attraction['place_id']}] {attraction['place_name']} ==> TripAdvisor [{location['name']}]")
        
        # Create a new DataFrame with the location_id and name
        new_entry = pd.DataFrame({
            "location_id": [location['location_id']], 
            "name": [location['name']],
            "province": attraction['province'],
            "place_id": attraction['place_id']
        })
        
        # Concatenate the new entry to the main DataFrame
        tripadvisor_central_attraction_locations = pd.concat([tripadvisor_central_attraction_locations, new_entry], ignore_index=True)
    
    # if index == 5:
    #     break

In [ ]:
tripadvisor_central_attraction_locations = pd.read_csv("dataset/central_tourism_attraction_locations_en.csv")

In [ ]:
tripadvisor_central_attraction_locations.drop_duplicates(subset=['location_id'], inplace=True)
tripadvisor_central_attraction_locations

In [14]:
# tripadvisor_central_attraction_locations.to_csv("TripAdvisor_Location_Ids.csv")
tripadvisor_central_attraction_locations = pd.read_csv("dataset/TripAdvisor_Location_Ids.csv")

In [ ]:
tripadvisor_central_attraction_locations

In [ ]:
tripadvisor_central_attraction_locations.info()

In [20]:
currentValue = tripadvisor_central_attraction_locations[tripadvisor_central_attraction_locations['location_id'] == 1831068]

currentIndex = currentValue.index[0] + 1
currentIndex

470

In [ ]:
valueAfterRecentlyIndex = tripadvisor_central_attraction_locations.loc[currentIndex + 1:]
valueAfterRecentlyIndex

In [4]:
import json 

with open("TripAdvisor_reviews_EN_Cluster-Set-1.json", "r", encoding="utf-8") as file:
    prev_review_en = json.load(file)

In [7]:
with open("TripAdvisor_reviews_EN_Cluster-Set-2.json", "r", encoding="utf-8") as file:
    prev_review_en = json.load(file)

In [8]:
json_keys = {int(list(item.keys())[0]) for item in prev_review_en}
len(json_keys)

456

In [3]:
tripadvisor_central_attraction_locations = pd.read_csv("./frontend/clustering_experiment/input/tag_embeddings.csv").drop(columns=["Unnamed: 0"], errors="ignore")
tripadvisor_central_attraction_locations

,location_id,name,description,web_url,latitude,longitude,website,write_review,rating,rating_image_url,...,rating_5_review_count,tags,trip_types_solo,trip_types_couples,trip_types_business,trip_types_family,trip_types_friends,cleaned_tags,tag_embeddings,cluster
0,456633,House of Opium,Located in the heart of the infamous Golden Tr...,https://www.tripadvisor.com/Attraction_Review-...,20.351446,100.081660,https://www.tourismthailand.org/Attraction/Hou...,https://www.tripadvisor.com/UserReview-g317131...,4.0,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,413.0,"History Museums, Specialty Museums",105.0,440.0,9.0,148.0,184.0,history museum specialty museum,[ 2.5900002e-03 -6.5010088e-04 -3.8178414e-03 ...,0
1,23933132,Opium Bar,NaN,https://www.tripadvisor.com/Attraction_Review-...,13.739190,100.508500,http://www.opiumbarbangkok.com/,https://www.tripadvisor.com/UserReview-g293916...,4.0,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,4.0,Bars & Clubs,0.0,3.0,0.0,0.0,2.0,bar club,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,21
2,7099963,Wat Phra That Doi Saket,NaN,https://www.tripadvisor.com/Attraction_Review-...,18.872380,99.139930,NaN,https://www.tripadvisor.com/UserReview-g196165...,4.5,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,44.0,Sacred & Religious Sites,9.0,26.0,0.0,14.0,21.0,sacred religious,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,15
3,1390125,Mae Ping River Cruise,Leave from the jetty at Wat Chai Mongkol and t...,https://www.tripadvisor.com/Attraction_Review-...,18.780819,99.005210,http://www.maepingrivercruise.com/,https://www.tripadvisor.com/UserReview-g293917...,3.5,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,102.0,Boat Tours,31.0,186.0,2.0,43.0,57.0,boat tour,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,10
4,547675,Pai River,NaN,https://www.tripadvisor.com/Attraction_Review-...,19.359318,98.445305,NaN,https://www.tripadvisor.com/UserReview-g303916...,4.0,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,52.0,Bodies of Water,30.0,56.0,1.0,15.0,46.0,body water,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1761,10053134,Chao Lao Beach,NaN,https://www.tripadvisor.com/Attraction_Review-...,12.533703,101.940470,NaN,https://www.tripadvisor.com/UserReview-g223726...,4.0,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,19.0,Beaches,3.0,18.0,1.0,13.0,11.0,beach,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,7
1762,23744675,Chao Lao Fish Bridge,NaN,https://www.tripadvisor.com/Attraction_Review-...,12.571852,101.923390,NaN,https://www.tripadvisor.com/UserReview-g323879...,4.0,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,0.0,Bridges,0.0,0.0,0.0,0.0,0.0,bridge,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,20
1763,10266462,Wat Burapa Temple,NaN,https://www.tripadvisor.com/Attraction_Review-...,15.230770,104.865680,NaN,https://www.tripadvisor.com/UserReview-g656472...,3.5,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,0.0,"Sacred & Religious Sites, Architectural Buildings",1.0,0.0,1.0,0.0,2.0,sacred religious architectural building,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,2
1764,12881708,Kung Wiman Beach,NaN,https://www.tripadvisor.com/Attraction_Review-...,12.608021,101.870415,NaN,https://www.tripadvisor.com/UserReview-g223726...,4.0,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,5.0,Beaches,1.0,4.0,0.0,4.0,3.0,beach,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,7
1765,23785341,Scenic Kung Wiman beach,NaN,https://www.tripadvisor.com/Attraction_Review-...,12.603604,101.878120,NaN,https://www.tripadvisor.com/UserReview-g209125...,3.0,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,0.0,Lookouts,0.0,0.0,0.0,0.0,0.0,lookout,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,14

In [6]:
filtered_df = tripadvisor_central_attraction_locations[
    ~tripadvisor_central_attraction_locations["location_id"].isin(json_keys)
]

In [9]:
filtered_df = filtered_df[
    ~filtered_df["location_id"].isin(json_keys)
]

In [10]:
filtered_df

,location_id,name,description,web_url,latitude,longitude,website,write_review,rating,rating_image_url,...,rating_5_review_count,tags,trip_types_solo,trip_types_couples,trip_types_business,trip_types_family,trip_types_friends,cleaned_tags,tag_embeddings,cluster
6,11895198,Tung Dok Bua Tong Doi Hua Mae Kum,NaN,https://www.tripadvisor.com/Attraction_Review-...,0.000000,0.00000,NaN,https://www.tripadvisor.com/UserReview-g223730...,5.0,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,1.0,Gardens,0.0,0.0,0.0,0.0,1.0,garden,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,16
9,10697181,Bo Nam Ron Krung Ching,NaN,https://www.tripadvisor.com/Attraction_Review-...,0.000000,0.00000,https://www.facebook.com/%E0%B8%9A%E0%B9%88%E0...,https://www.tripadvisor.com/UserReview-g223766...,0.0,NaN,...,0.0,Hot Springs & Geysers,0.0,0.0,0.0,0.0,0.0,hot spring geyser,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,2
15,12697822,Ban Chao Wichayen,NaN,https://www.tripadvisor.com/Attraction_Review-...,0.000000,0.00000,NaN,https://www.tripadvisor.com/UserReview-g303912...,0.0,NaN,...,0.0,"Historic Sites, Ancient Ruins",0.0,0.0,0.0,0.0,0.0,historic ancient ruin,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,2
17,6641096,Wat Lai,NaN,https://www.tripadvisor.com/Attraction_Review-...,0.000000,0.00000,NaN,https://www.tripadvisor.com/UserReview-g223714...,4.5,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,1.0,Points of Interest & Landmarks,0.0,0.0,0.0,0.0,2.0,NaN,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,-1
19,19254849,Wat Rai Tang Tong,NaN,https://www.tripadvisor.com/Attraction_Review-...,13.985253,99.84895,NaN,https://www.tripadvisor.com/UserReview-g223715...,4.0,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,0.0,Sacred & Religious Sites,0.0,0.0,0.0,0.0,0.0,sacred religious,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1741,4322623,Ban Phu Toei Hot Spring Park,NaN,https://www.tripadvisor.com/Attraction_Review-...,0.000000,0.00000,NaN,https://www.tripadvisor.com/UserReview-g223718...,0.0,NaN,...,0.0,Specialty Museums,0.0,0.0,0.0,0.0,0.0,specialty museum,[ 3.6465612e-03 1.1030026e-04 -5.0251749e-03 ...,0
1758,15560128,Khao Soi Dao Wildlife Sanctuary,NaN,https://www.tripadvisor.com/Attraction_Review-...,13.024640,102.08135,https://www.facebook.com/soidaoksd/,https://www.tripadvisor.com/UserReview-g223726...,5.0,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,2.0,Nature & Wildlife Areas,0.0,0.0,0.0,2.0,0.0,nature wildlife area,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,5
1762,23744675,Chao Lao Fish Bridge,NaN,https://www.tripadvisor.com/Attraction_Review-...,12.571852,101.92339,NaN,https://www.tripadvisor.com/UserReview-g323879...,4.0,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,0.0,Bridges,0.0,0.0,0.0,0.0,0.0,bridge,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,20
1763,10266462,Wat Burapa Temple,NaN,https://www.tripadvisor.com/Attraction_Review-...,15.230770,104.86568,NaN,https://www.tripadvisor.com/UserReview-g656472...,3.5,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,0.0,"Sacred & Religious Sites, Architectural Buildings",1.0,0.0,1.0,0.0,2.0,sacred religious architectural building,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,2
1765,23785341,Scenic Kung Wiman beach,NaN,https://www.tripadvisor.com/Attraction_Review-...,12.603604,101.87812,NaN,https://www.tripadvisor.com/UserReview-g209125...,3.0,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,0.0,Lookouts,0.0,0.0,0.0,0.0,0.0,lookout,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ...,14

In [11]:
tripadvisor_central_attraction_locations = filtered_df

In [12]:
tripadvisor_reviews = []

for k, location in tripadvisor_central_attraction_locations.iterrows():
    response = TripAdvisor_api.location_reviews(
        location['location_id'],
        "th"
    )
    
    try:
        reviews = response.json()['data']
        if len(reviews) == 0:
            continue
        
        review = {f"{location['location_id']}": reviews}
        tripadvisor_reviews.append(review)
        
        print(f" #{k + 1} >>> {location['location_id']}")
        
    except KeyError as e:
        print(f" #{k + 1} >>> {location['location_id']} ::: {e} {response}")
        continue
    
    # if (k == 5):
    #     break

 #7 >>> 11895198 ::: 'data' <Response [403]>
 #10 >>> 10697181 ::: 'data' <Response [403]>
 #16 >>> 12697822 ::: 'data' <Response [403]>
 #18 >>> 6641096 ::: 'data' <Response [403]>

KeyboardInterrupt:

In [38]:
len(tripadvisor_reviews)

261

In [39]:
tripadvisor_reviews

[{'456633': [{'id': 555329702,
    'lang': 'th',
    'location_id': 456633,
    'published_date': '2018-01-22T02:38:59Z',
    'rating': 4,
    'helpful_votes': 2,
    'rating_image_url': 'https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s4.0-66827-5.svg',
    'url': 'https://www.tripadvisor.com/ShowUserReviews-g317131-d456633-r555329702-Reviews-House_of_Opium-Chiang_Saen_Chiang_Rai_Province.html?m=66827#review555329702',
    'text': 'การบริการของพนักงานดี ภายในตกแต่งได้สวยงาม และได้ความรู้ มีการบรรยายทั้งภาษาอังกฤาและภาษาไทย โดยรวมเป็นมากกว่าคำว่าพิพิธภัณฑ์',
    'title': 'เป็นมากกว่าคำว่าพิพิธภัณฑ์',
    'trip_type': 'คู่รัก',
    'travel_date': '2018-01-31',
    'user': {'username': 'giffya2015',
     'user_location': {'id': '293916', 'name': 'Bangkok'},
     'avatar': {'thumbnail': 'https://media-cdn.tripadvisor.com/media/photo-t/1a/f6/f0/d5/default-avatar-2020-17.jpg',
      'small': 'https://media-cdn.tripadvisor.com/media/photo-l/1a/f6/f0/d5/default-avatar-2020-17.jpg',
      'medium': 'https://media-cdn.tripadvisor.com/media/photo-f/1a/f6/f0/d5/default-avatar-2020-17.jpg',
      'large': 'https://media-cdn.tripadvisor.com/media/photo-p/1a/f6/f0/d5/default-avatar-2020-17.jpg',
      'original': 'https://media-cdn.tripadvisor.com/media/photo-o/1a/f6/f0/d5/default-avatar-2020-17.jpg'}},
    'subratings': {}},
   {'id': 543783369,
    'lang': 'th',
    'location_id': 456633,
    'published_date': '2017-11-28T07:17:34Z',
    'rating': 5,
    'helpful_votes': 0,
    'rating_image_url': 'https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s5.0-66827-5.svg',
    'url': 'https://www.tripadvisor.com/ShowUserReviews-g317131-d456633-r543783369-Reviews-House_of_Opium-Chiang_Saen_Chiang_Rai_Province.html?m=66827#review543783369',
    'text': 'เป็นพิพิธภัณฑ์ที่ให้ข้อมูลเกี่ยวกับฝิ่นผูกเรื่องกับอารยธรรมของทั่วโลกได้เข้าใจง่ายมาก.. สามารถเชื่อมโยงทุกอย่างตามลำดับของการเข้าชมได้ไหลลื่น ในเรื่องของการตกแต่งก็ทันสมัยมากค่ะ รูปแบบการให้ข้อมูลในแต่ละห้องนิทรรศการมีความแตกต่างกัน ทำให้อยากเที่ยวชมให้ครบทุกห้อง.. ไม่น่าเบื่อ ใส่ใจรายละเอียดมากๆ',
    'title': 'พิพิธภัณฑ์ของภาครัฐที่ทำได้ดีมาก',
    'trip_type': 'เดินทางกับเพื่อน',
    'travel_date': '2017-11-30',
    'user': {'username': 'KiranarL',
     'user_location': {'id': 'null'},
     'avatar': {'thumbnail': 'https://media-cdn.tripadvisor.com/media/photo-t/11/63/75/38/kiranar-l.jpg',
      'small': 'https://media-cdn.tripadvisor.com/media/photo-l/11/63/75/38/kiranar-l.jpg',
      'medium': 'https://media-cdn.tripadvisor.com/media/photo-f/11/63/75/38/kiranar-l.jpg',
      'large': 'https://media-cdn.tripadvisor.com/media/photo-p/11/63/75/38/kiranar-l.jpg',
      'original': 'https://media-cdn.tripadvisor.com/media/photo-w/11/63/75/38/kiranar-l.jpg'}},
    'subratings': {}},
   {'id': 349537639,
    'lang': 'th',
    'location_id': 456633,
    'published_date': '2016-02-20T21:49:11Z',
    'rating': 4,
    'helpful_votes': 2,
    'rating_image_url': 'https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s4.0-66827-5.svg',
    'url': 'https://www.tripadvisor.com/ShowUserReviews-g317131-d456633-r349537639-Reviews-House_of_Opium-Chiang_Saen_Chiang_Rai_Province.html?m=66827#review349537639',
    'text': 'หอฝิ่นเป็นสถานที่ที่ควรไปชมสักครั้งหนึ่ง ค่าเข้าชมคนไทย 150 บาท ดูเหมือนแพง แต่คุ้มค่ามาก ภายในเก็บประวัติศาสตร์เกี่ยวกับฝิ่นตั้งแต่ยุคแรก ๆ มาจนปัจจุบัน มีเรื่องราวมากมายที่เกี่ยวฝิ่น, ฝิ่นในประเทศไทยและผู้ใช้ฝิ่นที่เป็นคนดัง มีเรื่องราวสอนใจได้อย่างดีมากมาย\n\nจัดแสดงได้ดีมาก ควรมาชมให้ได้สักครั้ง',
    'title': 'เป็นแหล่งเรียนรู้ที่มีบันทึกภาประวัติศาสตร์เอาไว้ได้ดี',
    'trip_type': 'เดินทางกับเพื่อน',
    'travel_date': '2015-11-30',
    'user': {'username': 'E24GJL',
     'user_location': {'id': '1308496', 'name': 'Chiang Mai Province'},
     'avatar': {'thumbnail': 'https://media-cdn.tripadvisor.com/media/photo-t/1a/f6/ed/00/default-avatar-2020-4.jpg',
      'small': 'https://media-cdn.tripadvisor.com/media/photo-l/1a/f6/ed/00/default-avatar-2020-4.jpg',
      'medium': 'https://media-cdn.tripadvisor.com/media/photo-f/1a/f6/ed/00/default-avatar-2020-4.jpg',
      'large': 'https://media-cdn.tripadvisor.com/media/photo-p/1a/f6/ed/00/default-avatar-2020-4.jpg',
      'original': 'https://media-cdn.tripadvisor.com/media/photo-o/1a/f6/ed/00/default-avatar-2020-4.jpg'}},
    'subratings': {}},
   {'id': 347878221,
    'lang': 'th',
    'location_id': 456633,
    'published_date': '2016-02-15T09:27:58Z',
    'rating': 4,
    'helpful_votes': 1,
    'rating_image_url': 'https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s4.0-66827-5.svg',
    'url': 'https://www.tripadvisor.com/ShowUserReviews-g317131-d456633-r347878221-Reviews-House_of_Opium-Chiang_Saen_Chiang_Rai_Province.html?m=66827#review347878221',
    'text': 'เป็นพิพิธภัณฑ์ที่รวบรวมทุกสิ่งทุกอย่างที่เกี่ยวกับการปลูกฝิ่น การค้า กระบวนการต่างๆ แหล่งค้าขายที่สำคัญด้วย',
    'title': 'พิพิธภัณฑ์ท่องถิ่น',
    'trip_type': 'คู่รัก',
    'travel_date': '2015-05-31',
    'user': {'username': 'chettakhun',
     'user_location': {'id': '293916', 'name': 'Bangkok'},
     'avatar': {'thumbnail': 'https://media-cdn.tripadvisor.com/media/photo-t/13/3c/c1/83/chettakhun.jpg',
      'small': 'https://media-cdn.tripadvisor.com/media/photo-l/13/3c/c1/83/chettakhun.jpg',
      'medium': 'https://media-cdn.tripadvisor.com/media/photo-f/13/3c/c1/83/chettakhun.jpg',
      'large': 'https://media-cdn.tripadvisor.com/media/photo-p/13/3c/c1/83/chettakhun.jpg',
      'original': 'https://media-cdn.tripadvisor.com/media/photo-w/13/3c/c1/83/chettakhun.jpg'}},
    'subratings': {}},
   {'id': 319533650,
    'lang': 'th',
    'location_id': 456633,
    'published_date': '2015-10-17T08:58:03Z',
    'rating': 5,
    'helpful_votes': 0,
    'rating_image_url': 'https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s5.0-66827-5.svg',
    'url': 'https://www.tripadvisor.com/ShowUserReviews-g317131-d456633-r319533650-Reviews-House_of_Opium-Chiang_Saen_Chiang_Rai_Province.html?m=66827#review319533650',
    'text': 'เราเข้าไปเยี่ยมชมพิพิธภัณฑ์หอฟิ่นเป็นครั้งแรกวิวรอบๆหอสวยงามมากค่าบัตรเข้าชมราคาคนไทย 150 บาท ราคาชาวต่างชาติ 300 บาท การเข้าเยี่ยมชมข้างในมีข้อห้ามถ่ายภาพแต่มีเจ้าหน้าที่คอยแนะนำที่ดีคุ้มค่าราคาใช้เวลาในการเข้าชมเกือบชั่วโมงประทับใจได้ความรู้',
    'title': 'Amazing',
    'trip_type': 'คู่รัก',
    'travel_date': '2015-10-31',
    'user': {'username': 'ketyada',
     'user_location': {'id': '297920',
      'name': 'Chiang Rai, Chiang Rai Province'},
     'avatar': {'thumbnail': 'https://media-cdn.tripadvisor.com/media/photo-t/19/57/f9/36/avatar.jpg',
      'small': 'https://media-cdn.tripadvisor.com/media/photo-l/19/57/f9/36/avatar.jpg',
      'medium': 'https://media-cdn.tripadvisor.com/media/photo-f/19/57/f9/36/avatar.jpg',
      'large': 'https://media-cdn.tripadvisor.com/media/photo-s/19/57/f9/36/avatar.jpg'}},
    'subratings': {}}]},
 {'7099963': [{'id': 737715581,
    'lang': 'th',
    'location_id': 7099963,
    'published_date': '2020-01-07T23:10:55Z',
    'rating': 4,
    'helpful_votes': 0,
    'rating_image_url': 'https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s4.0-66827-5.svg',
    'url': 'https://www.tripadvisor.com/ShowUserReviews-g1961657-d7099963-r737715581-Reviews-Wat_Phra_That_Doi_Saket-Doi_Saket.html?m=66827#review737715581',
    'text': 'เป็นอีกหนึ่งสถานที่ที่ไม่ควรพลาดเมื่อมาเที่ยวดอยสะเก็ด วัดพระธาตุดอยสะเก็ด ตั้งอยู่บนเขาและอยู่ใกล้แหล่งชุมชนติดกับตลาดสดดอยสะเก็ด ถ้าคนแข็งแรงดีก็สามารถเดินขึ้นบันไดนาคซึ่งเชื่อมต่อขึ้นไปถึงตัววัดพระธาตุดอยสะเก็ดได้แต่ทางขึ้นค่อนข้างสูงชัน อีกทางเลือกคือขับรถขึ้นไปด้านบนที่ตั้งของพระธาตุดอยสะเก็ด นอกจากกราบไหว้พระธาตุแล้วข้างบนยังสามารถมองเห็นวิวทิวทัศน์ได้อีกด้วย',
    'title': 'ขอพรไหว้พระธาตุ',
    'trip_type': 'NONE',
    'travel_date': '2020-01-31',
    'user': {'username': 'Kinu2015',
     'user_location': {'id': '293915', 'name': 'Thailand'},
     'avatar': {'thumbnail': 'https://media-cdn.tripadvisor.com/media/photo-t/07/ab/8f/71/walaiporn-k.jpg',
      'small': 'https://media-cdn.tripadvisor.com/media/photo-l/07/ab/8f/71/walaiporn-k.jpg',
      'medium': 'https://media-cdn.tripadvisor.com/media/photo-f/07/ab/8f/71/walaiporn-k.jpg',
      'large': 'https://media-cdn.tripadvisor.com/media/photo-s/07/ab/8f/71/walaiporn-k.jpg'}},
    'subratings': {}},
   {'id': 732815406,
    'lang': 'th',
    'location_id': 7099963,
    'published_date': '2019-12-15T10:00:48Z',
    'rating': 4,
    'helpful_votes': 0,
    'rating_image_url': 'https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s4.0-66827-5.svg',
    'url': 'https://www.tripadvisor.com/ShowUserReviews-g1961657-d7099963-r732815406-Reviews-Wat_Phra_That_Doi_Saket-Doi_Saket.html?m=66827#review732815406',
    'text': 'วัดสวย พระธาตุใหญ่มาก  ชอบเดินขึ้นบรรไดถือเป็นการออกกำลังไปในตัว\n\nมากราบไหว้ทุกเดือนเลยครับ  ข้างล่างเป็นตลาดของกินเยอะ',
    'title': 'วัดสวย',
    'trip_type': 'NONE',
    'travel_date': '2019-05-31',
    'user': {'username': 'baranoy',
     'user_location': {'id': 'null'},
     'avatar': {'thumbnail': 'https://media-cdn.tripadvisor.com/media/photo-t/1a/f6/f0/d5/default-avatar-2020-17.jpg',
      'small': 'https://media-cdn.tripadvisor.com/media/photo-l/1a/f6/f0/d5/default-avatar-2020-17.jpg',
      'medium': 'https://media-cdn.tripadvisor.com/media/photo-f/1a/f6/f0/d5/default-avatar-2020-17.jpg',
      'large': 'https://media-cdn.tripadvisor.com/media/photo-p/1a/f6/f0/d5/default-avatar-2020-17.jpg',
      'original': 'https://media-cdn.tripadvisor.com/media/photo-o/1a/f6/f0/d5/default-avatar-2020-17.jpg'}},
    'subratings': {}},
   {'id': 471633337,
    'lang': 'th',
    'location_id': 7099963,
    'published_date': '2017-03-31T10:29:13Z',
    'rating': 5,
    'helpful_votes': 1,
    'rating_image_url': 'https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s5.0-66827-5.svg',
    'url': 'https://www.tripadvisor.com/ShowUserReviews-g1961657-d7099963-r471633337-Reviews-Wat_Phra_That_Doi_Saket-Doi_Saket.html?m=66827#review471633337',
    'text': 'ที่ตั้งของพระธาตุจะอยู่นอกเมือง ไปทางอ.ดอยสะเก็ด ประมาณครึ่งชม. วัดจะอยู่แถว ๆ ตลาดดอยสะเก็ด พระธาตุอยู่ด้านบนสามารถชมวิวได้ด้วย',
    'title': 'ไหว้พระธาตุ',
    'trip_type': 'คู่รัก',
    'travel_date': '2017-03-31',
    'user': {'username': 'chettakhun',
     'user_location': {'id': '293916', 'name': 'Bangkok'},
     'avatar': {'thumbnail': 'https://media-cdn.tripadvisor.com/media/photo-t/13/3c/c1/83/chettakhun.jpg',
      'small': 'https://media-cdn.tripadvisor.com/media/photo-l/13/3c/c1/83/chettakhun.jpg',
      'medium': 'https://media-cdn.tripadvisor.com/media/photo-f/13/3c/c1/83/chettakhun.jpg',
      'large': 'https://media-cdn.tripadvisor.com/media/photo-p/13/3c/c1/83/chettakhun.jpg',
      'original': 'https://media-cdn.tripadvisor.com/media/photo-w/13/3c/c1/83/chettakhun.jpg'}},
    'subratings': {}},
   {'id': 412519732,
    'lang': 'th',
    'location_id': 7099963,
    'published_date': '2016-08-29T22:09:05Z',
    'rating': 4,
    'helpful_votes': 0,
    'rating_image_url': 'https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s4.0-66827-5.svg',
    'url': 'https://www.tripadvisor.com/ShowUserReviews-g1961657-d7099963-r412519732-Reviews-Wat_Phra_That_Doi_Saket-Doi_Saket.html?m=66827#review412519732',
    'text': 'มาเชียงใหม่ แวะเที่ยวอำเภอใกล้ๆ ขึ้นวัดพระธาตุดอยสะเก็ดหลังฝนตก แถมตอนเย็นด้วย เดินขึ้นบันไดกันจนหอบ แต่มีความสุข',
    'title': 'วัดพระธาตุดอยสะเก็ด',
    'trip_type': 'เดินทางกับเพื่อน',
    'travel_date': '2016-07-31',
    'user': {'username': 'crayondarm',
     'user_location': {'id': '293916', 'name': 'Bangkok'},
     'avatar': {'thumbnail': 'https://media-cdn.tripadvisor.com/media/photo-t/09/54/37/a1/crayondarm.jpg',
      'small': 'https://media-cdn.tripadvisor.com/media/photo-l/09/54/37/a1/crayondarm.jpg',
      'medium': 'https://media-cdn.tripadvisor.com/media/photo-f/09/54/37/a1/crayondarm.jpg',
      'large': 'https://media-cdn.tripadvisor.com/media/photo-s/09/54/37/a1/crayondarm.jpg',
      'original': 'https://media-cdn.tripadvisor.com/media/photo-o/09/54/37/a1/crayondarm.jpg'}},
    'subratings': {}},
   {'id': 351202332,
    'lang': 'th',
    'location_id': 7099963,
    'published_date': '2016-02-26T22:28:10Z',
    'rating': 4,
    'helpful_votes': 0,
    'rating_image_url': 'https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s4.0-66827-5.svg',
    'url': 'https://www.tripadvisor.com/ShowUserReviews-g1961657-d7099963-r351202332-Reviews-Wat_Phra_That_Doi_Saket-Doi_Saket.html?m=66827#review351202332',
    'text': 'วัดเก่าแก่คู่ดอยสะเก็ด สมัย ม.ปลาย เคยมาบวชเณรที่นี่ และก็แวะมาไหว้พระเป็นประจำ บริเวณวัดกว้างขวาง สิ่งก่อสร้างสวยงามและมีเพิ่มเติมจากเมื่อก่อนเยอะพอสมควร มีจุดชมวิวสวย ๆ ที่หน้าวัด มองเห็นวิวในเมืองได้สวยงามโดยเฉพาะยามเย็น',
    'title': 'พระธาตุสวย เก่าแก่คู่ดอยสะเก็ด',
    'trip_type': 'เดินทางคนเดียว',
    'travel_date': '2015-12-31',
    'user': {'username': 'E24GJL',
     'user_location': {'id': '1308496', 'name': 'Chiang Mai Province'},
     'avatar': {'thumbnail': 'https://media-cdn.tripadvisor.com/media/photo-t/1a/f6/ed/00/default-avatar-2020-4.jpg',
      'small': 'https://media-cdn.tripadvisor.com/media/photo-l/1a/f6/ed/00/default-avatar-2020-4.jpg',
      'medium': 'https://media-cdn.tripadvisor.com/media/photo-f/1a/f6/ed/00/default-avatar-2020-4.jpg',
      'large': 'https://media-cdn.tripadvisor.com/media/photo-p/1a/f6/ed/00/default-avatar-2020-4.jpg',
      'original': 'https://media-cdn.tripadvisor.com/media/photo-o/1a/f6/ed/00/default-avatar-2020-4.jpg'}},
    'subratings': {}}]},
 {'1390125': [{'id': 132279177,
    'lang': 'th',
    'location_id': 1390125,
    'published_date': '2012-06-18T22:36:25Z',
    'rating': 5,
    'helpful_votes': 5,
    'rating_image_url': 'https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s5.0-66827-5.svg',
    'url': 'https://www.tripadvisor.com/ShowUserReviews-g293917-d1390125-r132279177-Reviews-Mae_Ping_River_Cruise-Chiang_Mai.html?m=66827#review132279177',
    'text': 'เป็นทริปท่องเที่ยวในเมืองแต่แฝงไปด้วยกลิ่นอายของความเป็นอยู่ของคนไทยได้ดีทีเดียว(แบบชนบท) โดยนั่งเรือเอี้ยมจุ้นหรือเรือข้าว(เป็นเรือไม้สักโบราณ)หรือเป็นเรือหางยาว(ส่วนตัว)พนักงานคนขับจะเล่าและอธิบายไประว่างนั่งชมบรรยากาศของริมแม่น้ำปิง ประมาณ 45นาที หยุดที่บ้านชาวนาซึ่งบอกได้เลยว่าไม่ใช่สวนที่สวยงามและเป็นระเบียบหรอกนะ แต่เป็นสวนสมุนไพรพื้นบ้านและผักต่างๆที่ใช้ในครัวเรือนของคนไทยเราเป็นอย่างธรรมชาติ ท่นี่เค้าไม่ใช้สารเคมีทุกชนิด ยังมีการทำปุ๋ย อาหารสัตว์ และปราบศัตรูพืชโดยใช้วัตถุดิบจากพื้นบ้านทั้งสิ้น และที่นี่น้องๆจะอธิบายทุกอย่างเลยดูเป็นกันเองมาก หลังจากชมเสร็จน้องๆจะเชิญนั่งทานผลไม้รวม รวมถึงน้ำสมุนไพรสดทุกวันเช่น ตะไคร้ ลำใย ขิง และมะขาม หอมอร่อยจริงๆ(ฟรีครับ) แต่ที่ผมชอบมากอีกอย่างจะเป็นข้าวซอยบ้านชาวนา (หมู ปลา ไก่)รสชาดขอบอกว่าต้องลองเลยครับ ตามด้วยกาแฟสด อิ่มพอดีแถมเพื่อสุขภาพอีก นึกว่าจะกลับแล้วน้องเค้าพาไปดูภาพเก่าในอดีตเมืองเชียงใหม่ที่พิเศษภาพที่ถ่ายอัดโดย(ช่างภาพที่ถ่ายในอดีตด้วย) ชมอุปกรณ์การทำนาทุกชนิด อุปกรณ์การจับปลาที่หลากหลายในอดีต กลับล่ะคราวนี้ นั่งเรือกลับที่ท่าเรือโดยใช้เวลาทั้งหมดประมาณ 2ชั่วโมงครึ่ง ก็อกได้เลยว่า เป็นทริปพักผ่อนที่คุ้มค่าคุ้มราคาจริงๆ (คนละ 450บาท)แถมมีรถบริการ รับส่งฟรีด้วยครับ',
    'title': 'นั่งเรือกินลมเที่ยวชมบ้านชาวนา',
    'trip_type': 'ครอบครัว',
    'travel_date': '2012-04-30',
    'user': {'username': '141realtrip',
     'user_location': {'id': '293917', 'name': 'Chiang Mai'},
     'avatar': {'thumbnail': 'https://media-cdn.tripadvisor.com/media/photo-t/1a/f6/ec/a2/default-avatar-2020-3.jpg',
      'small': 'https://media-cdn.tripadvisor.com/media/photo-l/1a/f6/ec/a2/default-avatar-2020-3.jpg',
      'medium': 'https://media-cdn.tripadvisor.com/media/photo-f/1a/f6/ec/a2/default-avatar-2020-3.jpg',
      'large': 'https://media-cdn.tripadvisor.com/media/photo-p/1a/f6/ec/a2/default-avatar-2020-3.jpg',
      'original': 'https://media-cdn.tripadvisor.com/media/photo-o/1a/f6/ec/a2/default-avatar-2020-3.jpg'}},
    'subratings': {}}]},
 {'547675': [{'id': 732282027,
    'lang': 'th',
    'location_id': 547675,
    'published_date': '2019-12-12T14:10:20Z',
    'rating': 5,
    'helpful_votes': 0,
    'rating_image_url': 'https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s5.0-66827-5.svg',
    'url': 'https://www.tripadvisor.com/ShowUserReviews-g303916-d547675-r732282027-Reviews-Pai_River-Pai_Mae_Hong_Son_Province.html?m=66827#review732282027',
    'text': 'แม่น้ำปายแม่น้ำสายหลักของอำเภอปาย ที่ไหลผ่านตัวเมืองมีธรรมชาติที่สวยงาม โดยนักท่องเที่ยวนิยมมาชมวิวกันเป็นจำนวนมากที่บริเวณสะพานประวัติศาสตร์ท่าปาย',
    'title': 'แม่น้ำปาย',
    'trip_type': 'ครอบครัว',
    'travel_date': '2019-12-31',
    'user': {'username': 'vanapong',
     'user_location': {'id': '14053408',
      'name': 'Ko Kret, Nonthaburi Province'},
     'avatar': {'thumbnail': 'https://media-cdn.tripadvisor.com/media/photo-t/1b/a6/b0/23/vanapong.jpg',
      'small': 'https://media-cdn.tripadvisor.com/media/photo-l/1b/a6/b0/23/vanapong.jpg',
      'medium': 'https://media-cdn.tripadvisor.com/media/photo-f/1b/a6/b0/23/vanapong.jpg',
      'large': 'https://media-cdn.tripadvisor.com/media/photo-p/1b/a6/b0/23/vanapong.jpg',
      'original': 'https://media-cdn.tripadvisor.com/media/photo-m/1280/1b/a6/b0/23/vanapong.jpg'}},
    'subratings': {}},
   {'id': 555319792,
    'lang': 'th',
    'location_id': 547675,
    'published_date': '2018-01-22T02:01:07Z',
    'rating': 4,
    'helpful_votes': 0,
    'rating_image_url': 'https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s4.0-66827-5.svg',
    'url': 'https://www.tripadvisor.com/ShowUserReviews-g303916-d547675-r555319792-Reviews-Pai_River-Pai_Mae_Hong_Son_Province.html?m=66827#review555319792',
    'text': 'บรรยากาศชิวๆ ริมแม่น้ำปาย อากาศตอนเช้าจะสดชื่น วิวสวยมาก เงียบสงบ เหมาะแก่การมาพักผ่อน น้ำในแม่น้ำเย็นมาก',
    'title': 'แม่น้ำปาย',
    'trip_type': 'เดินทางกับเพื่อน',
    'travel_date': '2017-12-31',
    'user': {'username': 'Kameii_Tao',
     'user_location': {'id': '293915', 'name': 'Thailand'},
     'avatar': {'thumbnail': 'https://media-cdn.tripadvisor.com/media/photo-t/11/97/bb/ea/kameii-tao.jpg',
      'small': 'https://media-cdn.tripadvisor.com/media/photo-l/11/97/bb/ea/kameii-tao.jpg',
      'medium': 'https://media-cdn.tripadvisor.com/media/photo-f/11/97/bb/ea/kameii-tao.jpg',
      'large': 'https://media-cdn.tripadvisor.com/media/photo-s/11/97/bb/ea/kameii-tao.jpg'}},
    'subratings': {}},
   {'id': 495033774,
    'lang': 'th',
    'location_id': 547675,
    'published_date': '2017-06-22T02:58:27Z',
    'rating': 5,
    'helpful_votes': 0,
    'rating_image_url': 'https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s5.0-66827-5.svg',
    'url': 'https://www.tripadvisor.com/ShowUserReviews-g303916-d547675-r495033774-Reviews-Pai_River-Pai_Mae_Hong_Son_Province.html?m=66827#review495033774',
    'text': 'แม่น้ำเส้นหลักในเมืองปาย มีน้ำตลอดทั้งปี นักท่องเที่ยวนิยมเช่าห่วงยางแล้วนำไปเล่นในแม่น้ำทั้งชาวไทยและต่างชาติ',
    'title': 'แม่น้ำปาย',
    'trip_type': 'คู่รัก',
    'travel_date': '2016-07-31',
    'user': {'username': 'Beambus',
     'user_location': {'id': '293917', 'name': 'Chiang Mai'},
     'avatar': {'thumbnail': 'https://media-cdn.tripadvisor.com/media/photo-t/1a/f6/e5/2b/default-avatar-2020-52.jpg',
      'small': 'https://media-cdn.tripadvisor.com/media/photo-l/1a/f6/e5/2b/default-avatar-2020-52.jpg',
      'medium': 'https://media-cdn.tripadvisor.com/media/photo-f/1a/f6/e5/2b/default-avatar-2020-52.jpg',
      'large': 'https://media-cdn.tripadvisor.com/media/photo-p/1a/f6/e5/2b/default-avatar-2020-52.jpg',
      'original': 'https://media-cdn.tripadvisor.com/media/photo-o/1a/f6/e5/2b/default-avatar-2020-52.jpg'}},
    'subratings': {}},
   {'id': 459671288,
    'lang': 'th',
    'location_id': 547675,
    'published_date': '2017-02-14T10:32:58Z',
    'rating': 4,
    'helpful_votes': 0,
    'rating_image_url': 'https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/s4.0-66827-5.svg',

In [40]:
json_file_path = 'TripAdvisor_reviews_TH_Cluster-Set-1.json'
import json

# Open the file in write mode and save the JSON data
with open(json_file_path, 'w', encoding="utf-8") as json_file:
    json.dump(tripadvisor_reviews, json_file, indent=4)

In [18]:
# Initialize an empty list for json_var
json_var = []

# Data to be appended
data = [{"test_1": 3, "test_2": 2}]

# Loop through the range and append data to json_var
for i in range(5):
    json_var.append(data)

# Display the result
print(json_var)

[[{'test_1': 3, 'test_2': 2}], [{'test_1': 3, 'test_2': 2}], [{'test_1': 3, 'test_2': 2}], [{'test_1': 3, 'test_2': 2}], [{'test_1': 3, 'test_2': 2}]]

In [ ]:
# Import necessary libraries
import geopandas as gpd
import matplotlib.pyplot as plt

# Load the GeoJSON file
geojson_file = 'hook/data/thai_province_coordinates_geo.json'
gdf = gpd.read_file(geojson_file)

# Check for empty geometries and remove them
gdf = gdf[~gdf.is_empty]

# Ensure the CRS is set to WGS 84 (EPSG:4326)
if gdf.crs is None:
    gdf.set_crs(epsg=4326, inplace=True)

# Initialize a Matplotlib figure and axis
fig, ax = plt.subplots(figsize=(12, 8))

# Plot all provinces in light blue
gdf.plot(ax=ax, color='lightblue', edgecolor='black')

# Highlight Bangkok in red, checking if it exists in the data
bangkok = gdf[gdf['name'] == 'Bangkok Metropolis']
if not bangkok.empty:
    bangkok.plot(ax=ax, color='red', edgecolor='black')

# Set the aspect of the plot to equal to ensure accurate representation
ax.set_aspect('equal')

# Add title and labels
ax.set_title('Map of Thai Provinces with Bangkok Highlighted', fontsize=15)
ax.set_xlabel('Longitude', fontsize=12)
ax.set_ylabel('Latitude', fontsize=12)

# Show the plot
plt.show()