In [2]:
import pandas as pd
import numpy as np

In [28]:
attractions_df = pd.read_parquet('inputs/merged_tat_attractions.parquet')
attractions_df.head(5)

,place_id,place_name_th,introduction_th,category_name,category_id,latitude,longitude,postcode,thumbnail_url,tags,...,district_id,district_name_th,sub_district_id,sub_district_name_th,updated_at,introduction_en,place_name_en,province_name_en,district_name_en,sub_district_name_en
0,P03012583,ถ้ำมโหฬาร,อยู่ที่บ้านหนองหิน ตำบลหนองหิน อยู่ในบริเวณวัด...,สถานที่ท่องเที่ยว,3,17.10731,101.87997,42190.0,h,None,...,4214.0,หนองหิน,5102.0,หนองหิน,2024-07-16T20:03:56.009Z,"It is at Baan Nong Hin, Tambon Nong Hin, in Ma...",Tham Mahoran,Loei,Nong Hin,Nong Hin
1,P03014048,เสมาหินทราย บ้านปากแบ่งและบ้านนาหลัก,ที่บ้านนาหลัก เป็นเสมาหินปักคู่สองหลัก แบบที่ม...,สถานที่ท่องเที่ยว,3,17.48602,101.72230,42000.0,h,None,...,4201.0,เมืองเลย,4994.0,กุดป่อง,2024-07-16T20:03:55.442Z,None,Sandstone Semas of Ban Pak Baeng and Ban Na Lak,Loei,Mueang Loei,Kut Pong
2,P03025545,ศูนย์บริการนักท่องเที่ยววังกวาง,เป็นลานกางเต็นท์และบ้านพักของอุทยานฯ ซึ่งตั้งอ...,สถานที่ท่องเที่ยว,3,16.88681,101.78800,42180.0,h,None,...,4210.0,ภูกระดึง,5076.0,ศรีฐาน,2024-07-16T20:03:51.616Z,Accommodation and camping right near the peak ...,Wang Kwang Tourist Information Service Center,Loei,Phu Kradueng,Si Than
3,P03012596,อุทยานแห่งชาติภูสวนทราย,เป็นป่าดิบเขาเป็นพรมแดนธรรมชาติระหว่างแผ่นดินไ...,สถานที่ท่องเที่ยว,3,17.50356,100.93892,42170.0,h,อุทยานแห่งชาติภูสวนทราย,...,4206.0,นาแห้ว,5044.0,แสงภา,2024-07-16T20:03:51.358Z,None,Phu Suan Sai National Park,Loei,Na Haeo,Saeng Pha
4,P03001063,วัดท่าแขก วัดโบราณ,เป็นวัดเก่าแก่อยู่ริมฝั่งแม่น้ำโขง ห่างจากอำเภ...,สถานที่ท่องเที่ยว,3,17.90506,101.68336,42110.0,h,None,...,4203.0,เชียงคาน,5012.0,เชียงคาน,2024-07-16T20:03:50.031Z,None,"Wat Tha Khaek, The Ancient Temple",Loei,Chiang Khan,Chiang Khan

In [29]:
map_attractions_id = pd.read_parquet('inputs/TripAdvisor_Location_Ids.parquet')
map_attractions_id.head(5)

,location_id,name,province,place_id
0,2209612,Wat Ratchabophit,Bangkok,P03013220
1,2273363,Wat Rajapradit Sathitmahasimaram Rajaworavihara,Bangkok,P03013220
2,311043,Wat Phra Chetuphon,Bangkok,P03013220
3,317504,Temple Of Dawn (Wat Arun),Bangkok,P03013220
4,456322,Wat Umong,Bangkok,P03013220

In [30]:
attractions_df = attractions_df.merge(map_attractions_id[['place_id', 'location_id']], on='place_id', how='left')

In [31]:
attractions_df[attractions_df['location_id'].isna()]

,place_id,place_name_th,introduction_th,category_name,category_id,latitude,longitude,postcode,thumbnail_url,tags,...,district_name_th,sub_district_id,sub_district_name_th,updated_at,introduction_en,place_name_en,province_name_en,district_name_en,sub_district_name_en,location_id
0,P03012583,ถ้ำมโหฬาร,อยู่ที่บ้านหนองหิน ตำบลหนองหิน อยู่ในบริเวณวัด...,สถานที่ท่องเที่ยว,3,17.10731,101.879970,42190.0,h,None,...,หนองหิน,5102.0,หนองหิน,2024-07-16T20:03:56.009Z,"It is at Baan Nong Hin, Tambon Nong Hin, in Ma...",Tham Mahoran,Loei,Nong Hin,Nong Hin,NaN
1,P03014048,เสมาหินทราย บ้านปากแบ่งและบ้านนาหลัก,ที่บ้านนาหลัก เป็นเสมาหินปักคู่สองหลัก แบบที่ม...,สถานที่ท่องเที่ยว,3,17.48602,101.722300,42000.0,h,None,...,เมืองเลย,4994.0,กุดป่อง,2024-07-16T20:03:55.442Z,None,Sandstone Semas of Ban Pak Baeng and Ban Na Lak,Loei,Mueang Loei,Kut Pong,NaN
2,P03025545,ศูนย์บริการนักท่องเที่ยววังกวาง,เป็นลานกางเต็นท์และบ้านพักของอุทยานฯ ซึ่งตั้งอ...,สถานที่ท่องเที่ยว,3,16.88681,101.788000,42180.0,h,None,...,ภูกระดึง,5076.0,ศรีฐาน,2024-07-16T20:03:51.616Z,Accommodation and camping right near the peak ...,Wang Kwang Tourist Information Service Center,Loei,Phu Kradueng,Si Than,NaN
3,P03012596,อุทยานแห่งชาติภูสวนทราย,เป็นป่าดิบเขาเป็นพรมแดนธรรมชาติระหว่างแผ่นดินไ...,สถานที่ท่องเที่ยว,3,17.50356,100.938920,42170.0,h,อุทยานแห่งชาติภูสวนทราย,...,นาแห้ว,5044.0,แสงภา,2024-07-16T20:03:51.358Z,None,Phu Suan Sai National Park,Loei,Na Haeo,Saeng Pha,NaN
4,P03001063,วัดท่าแขก วัดโบราณ,เป็นวัดเก่าแก่อยู่ริมฝั่งแม่น้ำโขง ห่างจากอำเภ...,สถานที่ท่องเที่ยว,3,17.90506,101.683360,42110.0,h,None,...,เชียงคาน,5012.0,เชียงคาน,2024-07-16T20:03:50.031Z,None,"Wat Tha Khaek, The Ancient Temple",Loei,Chiang Khan,Chiang Khan,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5444,P03025745,แหล่งเรียนรู้โฮงคำสุวรรณเชษฐา,None,สถานที่ท่องเที่ยว,3,17.56720,102.285740,39270.0,None,None,...,สุวรรณคูหา,4483.0,สุวรรณคูหา,2024-06-03T20:00:46.879Z,None,None,Nong Bua Lam Phu,Suwannakhuha,Suwannakhuha,NaN
5445,P03025734,วัดมหาชัย,"ประดิษฐาน ""พระบาง"" พระพุทธรูปสำคัญคู่บ้านคู่เม...",สถานที่ท่องเที่ยว,3,17.20738,102.438290,39000.0,None,None,...,เมืองหนองบัวลำภู,4431.0,ลำภู,2024-06-03T20:00:33.654Z,None,None,Nong Bua Lam Phu,Mueang Nong Bua Lam Phu,Lam Phu,NaN
5446,P03010515,อนุสาวรีย์ไทยอาสาป้องกันชาติ (ทสปช.),None,สถานที่ท่องเที่ยว,3,17.36615,102.267420,39350.0,None,None,...,นากลาง,4441.0,กุดดินจี่,2024-06-03T20:00:24.475Z,None,National Defence Volunteers Monument,Nong Bua Lam Phu,Na Klang,Kut Din Chi,NaN
5447,P03014035,วัดถ้ำสุวรรณคูหา,None,สถานที่ท่องเที่ยว,3,17.60756,102.282970,39270.0,None,None,...,สุวรรณคูหา,4478.0,นาสี,2024-06-02T20:00:15.456Z,None,Tham Suwannakhuha Cave,Nong Bua Lam Phu,Suwannakhuha,Nasi,NaN
5448,P03025738,PC Cowboy Town,None,สถานที่ท่องเที่ยว,3,17.26886,102.534995,39000.0,None,None,...,เมืองหนองบัวลำภู,4433.0,โนนทัน,2023-10-10T21:00:09.883Z,None,None,Nong Bua Lam Phu,Mueang Nong Bua Lam Phu,Non Than,NaN

In [32]:
attractions_df['location_id'] = attractions_df['location_id'].fillna(0)

In [33]:
attractions_df

,place_id,place_name_th,introduction_th,category_name,category_id,latitude,longitude,postcode,thumbnail_url,tags,...,district_name_th,sub_district_id,sub_district_name_th,updated_at,introduction_en,place_name_en,province_name_en,district_name_en,sub_district_name_en,location_id
0,P03012583,ถ้ำมโหฬาร,อยู่ที่บ้านหนองหิน ตำบลหนองหิน อยู่ในบริเวณวัด...,สถานที่ท่องเที่ยว,3,17.10731,101.879970,42190.0,h,None,...,หนองหิน,5102.0,หนองหิน,2024-07-16T20:03:56.009Z,"It is at Baan Nong Hin, Tambon Nong Hin, in Ma...",Tham Mahoran,Loei,Nong Hin,Nong Hin,0.0
1,P03014048,เสมาหินทราย บ้านปากแบ่งและบ้านนาหลัก,ที่บ้านนาหลัก เป็นเสมาหินปักคู่สองหลัก แบบที่ม...,สถานที่ท่องเที่ยว,3,17.48602,101.722300,42000.0,h,None,...,เมืองเลย,4994.0,กุดป่อง,2024-07-16T20:03:55.442Z,None,Sandstone Semas of Ban Pak Baeng and Ban Na Lak,Loei,Mueang Loei,Kut Pong,0.0
2,P03025545,ศูนย์บริการนักท่องเที่ยววังกวาง,เป็นลานกางเต็นท์และบ้านพักของอุทยานฯ ซึ่งตั้งอ...,สถานที่ท่องเที่ยว,3,16.88681,101.788000,42180.0,h,None,...,ภูกระดึง,5076.0,ศรีฐาน,2024-07-16T20:03:51.616Z,Accommodation and camping right near the peak ...,Wang Kwang Tourist Information Service Center,Loei,Phu Kradueng,Si Than,0.0
3,P03012596,อุทยานแห่งชาติภูสวนทราย,เป็นป่าดิบเขาเป็นพรมแดนธรรมชาติระหว่างแผ่นดินไ...,สถานที่ท่องเที่ยว,3,17.50356,100.938920,42170.0,h,อุทยานแห่งชาติภูสวนทราย,...,นาแห้ว,5044.0,แสงภา,2024-07-16T20:03:51.358Z,None,Phu Suan Sai National Park,Loei,Na Haeo,Saeng Pha,0.0
4,P03001063,วัดท่าแขก วัดโบราณ,เป็นวัดเก่าแก่อยู่ริมฝั่งแม่น้ำโขง ห่างจากอำเภ...,สถานที่ท่องเที่ยว,3,17.90506,101.683360,42110.0,h,None,...,เชียงคาน,5012.0,เชียงคาน,2024-07-16T20:03:50.031Z,None,"Wat Tha Khaek, The Ancient Temple",Loei,Chiang Khan,Chiang Khan,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5444,P03025745,แหล่งเรียนรู้โฮงคำสุวรรณเชษฐา,None,สถานที่ท่องเที่ยว,3,17.56720,102.285740,39270.0,None,None,...,สุวรรณคูหา,4483.0,สุวรรณคูหา,2024-06-03T20:00:46.879Z,None,None,Nong Bua Lam Phu,Suwannakhuha,Suwannakhuha,0.0
5445,P03025734,วัดมหาชัย,"ประดิษฐาน ""พระบาง"" พระพุทธรูปสำคัญคู่บ้านคู่เม...",สถานที่ท่องเที่ยว,3,17.20738,102.438290,39000.0,None,None,...,เมืองหนองบัวลำภู,4431.0,ลำภู,2024-06-03T20:00:33.654Z,None,None,Nong Bua Lam Phu,Mueang Nong Bua Lam Phu,Lam Phu,0.0
5446,P03010515,อนุสาวรีย์ไทยอาสาป้องกันชาติ (ทสปช.),None,สถานที่ท่องเที่ยว,3,17.36615,102.267420,39350.0,None,None,...,นากลาง,4441.0,กุดดินจี่,2024-06-03T20:00:24.475Z,None,National Defence Volunteers Monument,Nong Bua Lam Phu,Na Klang,Kut Din Chi,0.0
5447,P03014035,วัดถ้ำสุวรรณคูหา,None,สถานที่ท่องเที่ยว,3,17.60756,102.282970,39270.0,None,None,...,สุวรรณคูหา,4478.0,นาสี,2024-06-02T20:00:15.456Z,None,Tham Suwannakhuha Cave,Nong Bua Lam Phu,Suwannakhuha,Nasi,0.0
5448,P03025738,PC Cowboy Town,None,สถานที่ท่องเที่ยว,3,17.26886,102.534995,39000.0,None,None,...,เมืองหนองบัวลำภู,4433.0,โนนทัน,2023-10-10T21:00:09.883Z,None,None,Nong Bua Lam Phu,Mueang Nong Bua Lam Phu,Non Than,0.0

In [34]:
attractions_df.to_parquet('inputs/final_tat_attractions.parquet', index=False, compression='gzip', engine='pyarrow')

In [1]:
import os
import re
import pandas as pd
import numpy as np
import emoji
import string
import nltk
from attacut import tokenize
from pythainlp import word_tokenize
from pythainlp.corpus.common import thai_stopwords
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import normalize
from sqlalchemy import create_engine, text
from dotenv import load_dotenv
from gensim.models import FastText
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [2]:
FINE_TUNED_DIR = '../pretained_or_finetune-models'
NLTK_DATA_PATH = f"{FINE_TUNED_DIR}/nltk_data"

nltk.data.path.append(NLTK_DATA_PATH)

stop_words = set(stopwords.words('english')) 
lemmatizer = WordNetLemmatizer()

BASE_DIR = "."
DATASET_DIR = os.path.join(BASE_DIR, "inputs")


def load_data_from_gcs(filename: str):
    # url = f"gs://my-streamlit-data/inputs/{filename}"
    url = f"{DATASET_DIR}/{filename}"
    return pd.read_parquet(url, engine="pyarrow")

In [3]:
tripadvisor_reviews_sentiment = load_data_from_gcs("sentiment_prediction.parquet")
tripadvisor_attractions_details = load_data_from_gcs("combined_details.parquet")
attractions_tags_cluster = load_data_from_gcs("cosine_clusters_V3.parquet")
tat_attractions = load_data_from_gcs("final_tat_attractions.parquet")
maps_tat_and_tripadvisor_ids = load_data_from_gcs("TripAdvisor_Location_Ids.parquet")

if tripadvisor_reviews_sentiment.empty or attractions_tags_cluster.empty or tat_attractions.empty:
    raise ValueError("❌ One or more required tables are empty. Please check your database.")

In [4]:

def clean_english_text(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)  # Remove numbers
    text = re.sub(r'[^a-z\s]', '', text)  # Remove special characters
    text = re.sub(r'\b(u|ur|b4)\b', 'you', text)  # Replace common abbreviations
    
    # Lowercasing
    text = text.lower()
    
    # Handling Emoji
    text = emoji.demojize(text)
    
    # Removing Punctuation
    text = ''.join([char for char in text if char not in string.punctuation])
    
    # Tokenization
    tokens = nltk.word_tokenize(text)
    
    # Removing Stop Words
    stop_words = set(stopwords.words('english'))
    tokens = [word for word in tokens if word not in stop_words]

    # Lemmatization
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(token) for token in tokens]

    # Join tokens back to a single string
    return ' '.join(tokens)

def clean_thai_text(text):
    """Preprocess Thai text by removing non-Thai characters and stopwords."""
    if not isinstance(text, str):
        return ""
    stopwords_list = set(thai_stopwords())
    text = re.sub(r"[^ก-๙\s]", "", text)  # Remove non-Thai characters
    tokens = word_tokenize(text)
    cleaned_tokens = [word for word in tokens if word not in stopwords_list]
    return " ".join(cleaned_tokens)

def vectorize_fasttext(text, model, vector_size=None):
    if not isinstance(text, str) or not text.strip():
        return np.zeros(model.vector_size if vector_size is None else vector_size, dtype=np.float32)

    try:
        tokens = tokenize(text)  # สมมุติว่า tokenize ดีแล้ว
    except Exception as e:
        print(f"⚠️ Tokenization error: {e}")
        return np.zeros(model.vector_size if vector_size is None else vector_size, dtype=np.float32)

    vectors = [model.wv[word] for word in tokens if word in model.wv.key_to_index]

    if not vectors:
        return np.zeros(model.vector_size if vector_size is None else vector_size, dtype=np.float32)

    return np.mean(vectors, axis=0)

In [5]:
tat_attractions.describe()

,category_id,latitude,longitude,postcode,province_id,district_id,sub_district_id,location_id
count,5449.0,5436.000000,5436.000000,5332.000000,5449.000000,5441.000000,5334.000000,5.449000e+03
mean,3.0,14.195466,100.654371,47073.165791,285.734447,4718.727624,5318.969066,2.618486e+06
std,0.0,3.192978,1.450623,27156.186333,155.776493,2678.716394,2988.628729,5.078967e+06
min,3.0,5.769720,97.646880,10100.000000,101.000000,1001.000000,1001.000000,0.000000e+00
25%,3.0,13.491075,99.832892,18260.000000,218.000000,2001.000000,2081.000000,0.000000e+00
50%,3.0,14.362600,100.462970,50160.000000,231.000000,5001.000000,6157.000000,0.000000e+00
75%,3.0,16.398780,101.162440,71180.000000,352.000000,7103.000000,8075.000000,3.856417e+06
max,3.0,20.441900,105.596670,96190.000000,590.000000,9610.000000,9904.000000,2.714283e+07

In [16]:
# filtered_attractions_df = tripadvisor_reviews_sentiment[
#     tripadvisor_reviews_sentiment["location_id"].isin(attractions_tags_cluster["location_id"])
# ]

filtered_attractions_df = tat_attractions

In [5]:
filtered_attractions_df = tat_attractions[
    tat_attractions["place_id"].isin(maps_tat_and_tripadvisor_ids["place_id"])
]

In [6]:
filtered_attractions_df.drop_duplicates(subset='place_id', inplace=True)

/var/folders/fk/449tdf_12hzd2r7ps4659q0m0000gn/T/ipykernel_20988/3389674517.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_attractions_df.drop_duplicates(subset='place_id', inplace=True)

In [7]:
filtered_attractions_df

,place_id,place_name_th,introduction_th,category_name,category_id,latitude,longitude,postcode,thumbnail_url,tags,...,district_name_th,sub_district_id,sub_district_name_th,updated_at,introduction_en,place_name_en,province_name_en,district_name_en,sub_district_name_en,location_id
214,P03005073,วัดพระบรมธาตุวรวิหาร,เป็นพระอารามหลวงชั้นโท เป็นวัดเก่าแก่คู่บ้านคู...,สถานที่ท่องเที่ยว,3,15.15922,100.15250,17000.0,h,None,...,เมืองชัยนาท,1901.0,ชัยนาท,2024-07-16T20:03:55.942Z,None,Phra Borommathat Wora Wihan Temple,Chainat,Mueang Chai Nat,Chai Nat,8814855.0
215,P03013611,สวนนกชัยนาท,None,สถานที่ท่องเที่ยว,3,15.20607,100.15236,17000.0,h,None,...,เมืองชัยนาท,1902.0,เขาท่าพระ,2024-07-16T20:03:46.903Z,This is located 4 kilometres before arriving i...,Chainat Bird Park,Chainat,Mueang Chai Nat,Khao Tha Phra,4243478.0
217,P03010754,วัดกรุณา,เป็นวัดที่อยู่ใกล้เขื่อนเจ้าพระยา ตรงข้ามบ้านร...,สถานที่ท่องเที่ยว,3,15.14661,100.17912,17150.0,h,None,...,สรรพยา,1930.0,บางหลวง,2024-07-16T20:03:43.371Z,None,Wat Karuna,Chainat,Sapphaya,Bang Luang,4322552.0
219,P03012143,เขื่อนเจ้าพระยา,เป็นเขื่อนขนาดใหญ่แห่งแรกของประเทศ ตั้งอยู่ที่...,สถานที่ท่องเที่ยว,3,15.15893,100.18004,17150.0,h,None,...,สรรพยา,1930.0,บางหลวง,2024-07-16T20:03:39.282Z,None,Chao Phraya Dam,Chainat,Sapphaya,Bang Luang,4322699.0
220,P03014371,วัดดอนตูมกมลาวาส,None,สถานที่ท่องเที่ยว,3,15.26728,100.02742,17120.0,h,None,...,วัดสิงห์,1917.0,หนองบัว,2024-07-16T20:03:37.798Z,None,Wat Don Tum Kamalawat,Chainat,Wat Sing,Nong Bua,2513887.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5201,P03012869,พระพุทธเกตุมงคล (หลวงพ่อโตตะพานหิน) วัดเทวปราสาท,เป็นพระพุทธรูปปางประทานพร หน้าตักกว้าง 20 เมตร...,สถานที่ท่องเที่ยว,3,16.22143,100.41971,66110.0,h,None,...,ตะพานหิน,7690.0,ตะพานหิน,2024-07-01T20:00:08.662Z,None,Phra Buddha Ket Mongkhon,Phichit,Taphan Hin,Taphan Hin,4925765.0
5203,P03014195,วัดทับคล้อ (สวนพระโพธิสัตว์),วัดทับคล้อ (สวนพระโพธิ์สัตว์) ตั้งอยู่ตำบลทับค...,สถานที่ท่องเที่ยว,3,16.16167,100.59667,66150.0,h,None,...,ทับคล้อ,7747.0,ทับคล้อ,2024-07-01T20:00:07.498Z,"Located at Tub Klo Subdistrict, Tub Klo temple...",Wat Tub Klo (Bodhisattva Garden),Phichit,Tap Khlo,Thap Khlo,19835213.0
5211,P03018368,ชุมชนย่านเก่าวังกรด,None,สถานที่ท่องเที่ยว,3,16.39674,100.38952,66000.0,h,None,...,เมืองพิจิตร,7660.0,บ้านบุ่ง,2024-06-03T20:01:42.409Z,None,Chumchon Yann Kao Wangkrod,Phichit,Mueang Phichit,Ban Bung,2401021.0
5227,P03017631,เกาะศรีมาลา,None,สถานที่ท่องเที่ยว,3,16.43833,100.35000,66000.0,None,"เกาะศรีมาลา,พิจิตร",...,เมืองพิจิตร,7651.0,ในเมือง,2024-06-03T20:00:11.810Z,None,Ko Si Mala,Phichit,Mueang Phichit,Nai Mueang,16812451.0
5229,P03017653,วัดใหม่ปลายห้วย,None,สถานที่ท่องเที่ยว,3,16.37246,100.08917,66140.0,None,"พิจิตร,วัดใหม่ปลายห้วย",...,สามง่าม,7743.0,เนินปอ,2024-06-02T20:00:17.463Z,None,Wat Mai Plai Houy,Phichit,Sam Ngam,Noen Po,2073963.0

In [8]:
filtered_attractions_df["cleaned_introduction_th"] = filtered_attractions_df["introduction_th"].apply(lambda x: clean_thai_text(x) if isinstance(x, str) else "")
filtered_attractions_df["cleaned_place_name_th"] = filtered_attractions_df["place_name_th"].apply(lambda x: clean_thai_text(x) if isinstance(x, str) else "")

filtered_attractions_df["merged_attraction_content_th"] = (
    filtered_attractions_df["cleaned_introduction_th"].fillna("") + " " +
    filtered_attractions_df["cleaned_place_name_th"].fillna("")
).str.strip()

filtered_attractions_df["cleaned_introduction_en"] = filtered_attractions_df["introduction_en"].apply(lambda x: clean_english_text(x) if isinstance(x, str) else "")
filtered_attractions_df["cleaned_place_name_en"] = filtered_attractions_df["place_name_en"].apply(lambda x: clean_english_text(x) if isinstance(x, str) else "")

filtered_attractions_df["merged_attraction_content_en"] = (
    filtered_attractions_df["cleaned_introduction_en"].fillna("") + " " +
    filtered_attractions_df["cleaned_place_name_en"].fillna("")
).str.strip()

/var/folders/fk/449tdf_12hzd2r7ps4659q0m0000gn/T/ipykernel_20988/1472089885.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_attractions_df["cleaned_introduction_th"] = filtered_attractions_df["introduction_th"].apply(lambda x: clean_thai_text(x) if isinstance(x, str) else "")
/var/folders/fk/449tdf_12hzd2r7ps4659q0m0000gn/T/ipykernel_20988/1472089885.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_attractions_df["cleaned_place_name_th"] = filtered_attractions_df["place_name_th"].apply(lambda x: clean_thai_text(x) if isinstance(x, str) else "")
/var/folders/fk/449tdf_12hzd2r7ps4659q0m0000gn/T/ipykernel_20988/1472089885.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_attractions_df["merged_attraction_content_th"] = (
/var/folders/fk/449tdf_12hzd2r7ps4659q0m0000gn/T/ipykernel_20988/1472089885.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_attractions_df["cleaned_introduction_en"] = filtered_attractions_df["introduction_en"].apply(lambda x: clean_english_text(x) if isinstance(x, str) else "")
/var/folders/fk/449tdf_12hzd2r7ps4659q0m0000gn/T/ipykernel_20988/1472089885.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_attractions_df["cleaned_place_name_en"] = filtered_attractions_df["place_name_en"].apply(lambda x: clean_english_text(x) if isinstance(x, str) else "")
/var/folders/fk/449tdf_12hzd2r7ps4659q0m0000gn/T/ipykernel_20988/1472089885.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_attractions_df["merged_attraction_content_en"] = (

In [9]:
TH_filtered_attractions_df = filtered_attractions_df[filtered_attractions_df["merged_attraction_content_th"].str.strip() != ""]
EN_filtered_attractions_df = filtered_attractions_df[filtered_attractions_df["merged_attraction_content_en"].str.strip() != ""]

TH_tokenized_sentences = [word_tokenize(text) for text in TH_filtered_attractions_df["merged_attraction_content_th"] if isinstance(text, str) and text.strip()]
EN_tokenized_sentences = [word_tokenize(text) for text in EN_filtered_attractions_df["merged_attraction_content_en"] if isinstance(text, str) and text.strip()]

In [12]:
filtered_attractions_df.to_parquet('filtered_attractions_df.parquet', index=False, compression='gzip', engine='pyarrow')

In [22]:
TH_filtered_attractions_df["merged_attraction_content_th"]

214     พระอารามหลวง ชั้น โท   วัด เก่าแก่ คู่บ้านคู่เ...
215                                          สวนนก ชัยนาท
217     วัด ที่อยู่ เขื่อน เจ้าพระยา   ตรงข้าม บ้านรับ...
219     เขื่อน ขนาดใหญ่ ประเทศ   ตั้งอยู่ บริเวณ คุ้ง ...
220                                 วัด ดอน ตูม กม ลาวา ส
                              ...
5201    พระพุทธรูป ปาง ประทาน พร   หน้าตัก    เมตร    ...
5203    วัด ทับ คล้อ   สวน พระ โพธิ์ สัตว์   ตั้งอยู่ ...
5211                              ชุมชน ย่าน เก่า วัง กรด
5227                                        เกาะ ศรี มาลา
5229                                        วัด ปลาย ห้วย
Name: merged_attraction_content_th, Length: 603, dtype: object

In [11]:
TH_attraction_vectors = []

if not TH_tokenized_sentences:
    print("❌ No tokenized sentences available for Fasttext training. Ensure preprocessing is correct.")
else:
    TH_fasttext_model = FastText(
        vector_size=300,
        window=10,
        min_count=2,
        workers=4,
        sg=1,
        min_n=2,
        max_n=6,
        negative=10
    )
    if TH_tokenized_sentences:
        TH_fasttext_model.build_vocab(TH_tokenized_sentences)
        TH_fasttext_model.train(TH_tokenized_sentences, total_examples=TH_fasttext_model.corpus_count, epochs=20)
    else:
        print("⚠️ No TH data for FastText training.")
        
TH_attraction_vectors = np.array([
    vectorize_fasttext(text, TH_fasttext_model) 
    for text in filtered_attractions_df["merged_attraction_content_th"]
], dtype=np.float32)

/Users/ittichaiboonyarakthunya/Documents/WorkDir/developments/IS_Project/.venv/lib/python3.12/site-packages/attacut/models/__init__.py:60: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(model_path, map_location="cpu"))

In [12]:
EN_attraction_vectors = []

if not EN_tokenized_sentences:
    print("❌ No tokenized sentences available for Fasttext training. Ensure preprocessing is correct.")
else:
    EN_fasttext_model = FastText(
        vector_size=300,
        window=5,  # อังกฤษใช้ window เล็กกว่าหน่อย
        min_count=2,
        workers=4,
        sg=1,
        min_n=2,
        max_n=6,
        negative=10
    )

    if EN_tokenized_sentences:
        EN_fasttext_model.build_vocab(EN_tokenized_sentences)
        EN_fasttext_model.train(EN_tokenized_sentences, total_examples=EN_fasttext_model.corpus_count, epochs=20)
    else:
        print("⚠️ No EN data for FastText training.")
        
EN_attraction_vectors = np.array([
    vectorize_fasttext(text, EN_fasttext_model) 
    for text in filtered_attractions_df["merged_attraction_content_en"]
], dtype=np.float32)

In [15]:
EN_fasttext_model.save("EN_fasttext_model.model")
TH_fasttext_model.save("TH_fasttext_model.model")

In [13]:
np.save("TH_attraction_vectors.npy", TH_attraction_vectors)
np.save("EN_attraction_vectors.npy", EN_attraction_vectors)

In [ ]:
TH_attraction_vectors = np.load("th_attraction_vectors.npy")
EN_attraction_vectors = np.load("EN_attraction_vectors.npy")

In [67]:
filtered_attractions_df[filtered_attractions_df['location_id'] > 0]

,place_id,place_name_th,introduction_th,category_name,category_id,latitude,longitude,postcode,thumbnail_url,tags,...,province_name_en,district_name_en,sub_district_name_en,location_id,cleaned_introduction_th,cleaned_place_name_th,merged_attraction_content_th,cleaned_introduction_en,cleaned_place_name_en,merged_attraction_content_en
214,P03005073,วัดพระบรมธาตุวรวิหาร,เป็นพระอารามหลวงชั้นโท เป็นวัดเก่าแก่คู่บ้านคู...,สถานที่ท่องเที่ยว,3,15.15922,100.15250,17000.0,h,None,...,Chainat,Mueang Chai Nat,Chai Nat,8814855.0,พระอารามหลวง ชั้น โท วัด เก่าแก่ คู่บ้านคู่เ...,วัด พระบรมธาตุ วรวิหาร,พระอารามหลวง ชั้น โท วัด เก่าแก่ คู่บ้านคู่เ...,,phra borommathat wora wihan temple,phra borommathat wora wihan temple
215,P03013611,สวนนกชัยนาท,None,สถานที่ท่องเที่ยว,3,15.20607,100.15236,17000.0,h,None,...,Chainat,Mueang Chai Nat,Khao Tha Phra,4243478.0,,สวนนก ชัยนาท,สวนนก ชัยนาท,located kilometre arriving chainat bird specie...,chainat bird park,located kilometre arriving chainat bird specie...
217,P03010754,วัดกรุณา,เป็นวัดที่อยู่ใกล้เขื่อนเจ้าพระยา ตรงข้ามบ้านร...,สถานที่ท่องเที่ยว,3,15.14661,100.17912,17150.0,h,None,...,Chainat,Sapphaya,Bang Luang,4322552.0,วัด ที่อยู่ เขื่อน เจ้าพระยา ตรงข้าม บ้านรับ...,วัด กรุณา,วัด ที่อยู่ เขื่อน เจ้าพระยา ตรงข้าม บ้านรับ...,,wat karuna,wat karuna
219,P03012143,เขื่อนเจ้าพระยา,เป็นเขื่อนขนาดใหญ่แห่งแรกของประเทศ ตั้งอยู่ที่...,สถานที่ท่องเที่ยว,3,15.15893,100.18004,17150.0,h,None,...,Chainat,Sapphaya,Bang Luang,4322699.0,เขื่อน ขนาดใหญ่ ประเทศ ตั้งอยู่ บริเวณ คุ้ง ...,เขื่อน เจ้าพระยา,เขื่อน ขนาดใหญ่ ประเทศ ตั้งอยู่ บริเวณ คุ้ง ...,,chao phraya dam,chao phraya dam
220,P03014371,วัดดอนตูมกมลาวาส,None,สถานที่ท่องเที่ยว,3,15.26728,100.02742,17120.0,h,None,...,Chainat,Wat Sing,Nong Bua,2513887.0,,วัด ดอน ตูม กม ลาวา ส,วัด ดอน ตูม กม ลาวา ส,,wat tum kamalawat,wat tum kamalawat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5201,P03012869,พระพุทธเกตุมงคล (หลวงพ่อโตตะพานหิน) วัดเทวปราสาท,เป็นพระพุทธรูปปางประทานพร หน้าตักกว้าง 20 เมตร...,สถานที่ท่องเที่ยว,3,16.22143,100.41971,66110.0,h,None,...,Phichit,Taphan Hin,Taphan Hin,4925765.0,พระพุทธรูป ปาง ประทาน พร หน้าตัก เมตร ...,พระพุทธ เกตุ มงคล หลวงพ่อ ตะพาน หิน วัด เท...,พระพุทธรูป ปาง ประทาน พร หน้าตัก เมตร ...,,phra buddha ket mongkhon,phra buddha ket mongkhon
5203,P03014195,วัดทับคล้อ (สวนพระโพธิสัตว์),วัดทับคล้อ (สวนพระโพธิ์สัตว์) ตั้งอยู่ตำบลทับค...,สถานที่ท่องเที่ยว,3,16.16167,100.59667,66150.0,h,None,...,Phichit,Tap Khlo,Thap Khlo,19835213.0,วัด ทับ คล้อ สวน พระ โพธิ์ สัตว์ ตั้งอยู่ ...,วัด ทับ คล้อ สวน พระโพธิสัตว์,วัด ทับ คล้อ สวน พระ โพธิ์ สัตว์ ตั้งอยู่ ...,located tub klo subdistrict tub klo temple pro...,wat tub klo bodhisattva garden,located tub klo subdistrict tub klo temple pro...
5211,P03018368,ชุมชนย่านเก่าวังกรด,None,สถานที่ท่องเที่ยว,3,16.39674,100.38952,66000.0,h,None,...,Phichit,Mueang Phichit,Ban Bung,2401021.0,,ชุมชน ย่าน เก่า วัง กรด,ชุมชน ย่าน เก่า วัง กรด,,chumchon yann kao wangkrod,chumchon yann kao wangkrod
5227,P03017631,เกาะศรีมาลา,None,สถานที่ท่องเที่ยว,3,16.43833,100.35000,66000.0,None,"เกาะศรีมาลา,พิจิตร",...,Phichit,Mueang Phichit,Nai Mueang,16812451.0,,เกาะ ศรี มาลา,เกาะ ศรี มาลา,,ko si mala,ko si mala
5229,P03017653,วัดใหม่ปลายห้วย,None,สถานที่ท่องเที่ยว,3,16.37246,100.08917,66140.0,None,"พิจิตร,วัดใหม่ปลายห้วย",...,Phichit,Sam Ngam,Noen Po,2073963.0,,วัด ปลาย ห้วย,วัด ปลาย ห้วย,,wat mai plai houy,wat mai plai houy

In [24]:
input_text ="ร่มรื่นธรรมชาติ"
language="TH"

cleaned_input_text = ""
if (language == "TH" and TH_attraction_vectors.size == 0) or (language == "EN" and EN_attraction_vectors.size == 0):
    print("❌ No vectors available for similarity search!")


if language == "TH":
    attraction_vectors = TH_attraction_vectors
    fasttext_model = TH_fasttext_model
    cleaned_input_text = clean_thai_text(input_text)
elif language == "EN":
    attraction_vectors = EN_attraction_vectors
    fasttext_model = EN_fasttext_model
    cleaned_input_text = clean_english_text(input_text)
else:
    raise ValueError("❌ Unsupported language. Use 'TH' or 'EN'.")

In [25]:
input_vector = vectorize_fasttext(cleaned_input_text, fasttext_model)
input_vector = normalize(input_vector.reshape(1, -1))  # Normalize input vector

similarity_scores = cosine_similarity(input_vector, attraction_vectors)[0]

In [26]:
top_5_indices = np.argsort(similarity_scores)[::-1][:5]

print("🔍 Top 5 Indices:", top_5_indices)
print("✅ Similarity Scores:", similarity_scores[top_5_indices])

🔍 Top 5 Indices: [ 43 576 287 142 424]
✅ Similarity Scores: [0.9563435 0.9490386 0.9487766 0.9480233 0.9436252]

In [27]:
results = []
for idx in top_5_indices:
    row = filtered_attractions_df.iloc[idx]

    place_id = row["place_id"]
    place_name = row["place_name_th"]
    similarity_score = similarity_scores[idx]
    merged_content = ""
    
    if language == "TH":
        merged_content = row["merged_attraction_content_th"]
    elif language == "EN":
        merged_content = row["merged_attraction_content_en"]
    else:
        merged_content = "N/A"
        
    result_review = maps_tat_and_tripadvisor_ids[maps_tat_and_tripadvisor_ids["place_id"] == place_id]
    location_id = result_review["location_id"].tolist() if not result_review.empty else []
    
    print(f"🔍 [Score: {similarity_score:.3f}] Place ID: {place_id} / Place Name {place_name} >>>>>>>>> [location_id: {location_id}]")

🔍 [Score: 0.956] Place ID: P03012873 / Place Name จุดชมวิวพระอาทิตย์ตก (ถ้ำผาหงษ์) >>>>>>>>> [location_id: [12166100, 3448295, 8614647]]
🔍 [Score: 0.949] Place ID: P03006648 / Place Name น้ำตกชาติตระการ >>>>>>>>> [location_id: [13340265, 13340266]]
🔍 [Score: 0.949] Place ID: P03015636 / Place Name ไร่องุ่นอำเภอมวกเหล็ก >>>>>>>>> [location_id: [2436640, 13376284]]
🔍 [Score: 0.948] Place ID: P03018393 / Place Name เพิ่มทรัพย์เห็ดฟาร์ม >>>>>>>>> [location_id: [7134758, 10644322, 2640501]]
🔍 [Score: 0.944] Place ID: P03012816 / Place Name อาคารแสดงพันธุ์สัตว์น้ำบึงบอระเพ็ดเฉลิมพระเกียรติ 80 พรรษา >>>>>>>>> [location_id: [4322796]]

In [ ]:
tripadvisor_attractions_details

,location_id,name,description,web_url,latitude,longitude,website,write_review,rating,rating_image_url,...,rating_2_review_count,rating_3_review_count,rating_4_review_count,rating_5_review_count,tags,trip_types_solo,trip_types_couples,trip_types_business,trip_types_family,trip_types_friends
0,456633,House of Opium,Located in the heart of the infamous Golden Tr...,https://www.tripadvisor.com/Attraction_Review-...,20.351446,100.081660,https://www.tourismthailand.org/Attraction/Hou...,https://www.tripadvisor.com/UserReview-g317131...,4.0,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,34,210,363,413,"History Museums, Specialty Museums",105,440,9,148,184
1,23933132,Opium Bar,None,https://www.tripadvisor.com/Attraction_Review-...,13.739190,100.508500,http://www.opiumbarbangkok.com/,https://www.tripadvisor.com/UserReview-g293916...,4.0,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,0,1,0,4,Bars & Clubs,0,3,0,0,2
2,7099963,Wat Phra That Doi Saket,None,https://www.tripadvisor.com/Attraction_Review-...,18.872380,99.139930,None,https://www.tripadvisor.com/UserReview-g196165...,4.5,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,0,5,31,44,Sacred & Religious Sites,9,26,0,14,21
3,1390125,Mae Ping River Cruise,Leave from the jetty at Wat Chai Mongkol and t...,https://www.tripadvisor.com/Attraction_Review-...,18.780819,99.005210,http://www.maepingrivercruise.com/,https://www.tripadvisor.com/UserReview-g293917...,3.5,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,43,98,127,102,Boat Tours,31,186,2,43,57
4,547675,Pai River,None,https://www.tripadvisor.com/Attraction_Review-...,19.359318,98.445305,None,https://www.tripadvisor.com/UserReview-g303916...,4.0,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,6,46,58,52,Bodies of Water,30,56,1,15,46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1761,10053134,Chao Lao Beach,None,https://www.tripadvisor.com/Attraction_Review-...,12.533703,101.940470,None,https://www.tripadvisor.com/UserReview-g223726...,4.0,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,3,10,25,19,Beaches,3,18,1,13,11
1762,23744675,Chao Lao Fish Bridge,None,https://www.tripadvisor.com/Attraction_Review-...,12.571852,101.923390,None,https://www.tripadvisor.com/UserReview-g323879...,4.0,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,0,0,1,0,Bridges,0,0,0,0,0
1763,10266462,Wat Burapa Temple,None,https://www.tripadvisor.com/Attraction_Review-...,15.230770,104.865680,None,https://www.tripadvisor.com/UserReview-g656472...,3.5,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,0,3,1,0,"Sacred & Religious Sites, Architectural Buildings",1,0,1,0,2
1764,12881708,Kung Wiman Beach,None,https://www.tripadvisor.com/Attraction_Review-...,12.608021,101.870415,None,https://www.tripadvisor.com/UserReview-g223726...,4.0,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,0,1,7,5,Beaches,1,4,0,4,3
1765,23785341,Scenic Kung Wiman beach,None,https://www.tripadvisor.com/Attraction_Review-...,12.603604,101.878120,None,https://www.tripadvisor.com/UserReview-g209125...,3.0,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,0,1,0,0,Lookouts,0,0,0,0,0

:

In [10]:
tripadvisor_reviews_sentiment[tripadvisor_reviews_sentiment['location_id'].isin("24005787")]

TypeError: only list-like objects are allowed to be passed to isin(), you passed a `str`